name: homepage

services:
  homepage:
    build: .
    container_name: homepage
    restart: unless-stopped
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`joshuae.dev`)"
      - "traefik.http.routers.homepage.entrypoints=http"

networks:
  proxy-net:
    external: true
